services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: postgres
    ports:
      - '8080:8080'
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  - db_data:/var/lib/postgresql/data
